name: test_layout
description: This is a test application for testing a layout for random user API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
